#!/bin/sh
until curl -X PUT localhost:8083/connectors/elasticsearch-connector-ostAnswer/config -H "Content-Type: application/json" -d '{"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", "connection.url": "http://elasticsearch:9200", "tasks.max": "1", "topics": "ostAnswer", "name": "elasticsearch-connector-ostAnswer", "type.name": "_doc", "value.converter": "org.apache.kafka.connect.json.JsonConverter", "value.converter.schemas.enable": "false", "schema.ignore": "true", "key.ignore": "true"}'
do
sleep 10
done
curl -X PUT localhost:8083/connectors/elasticsearch-connector-environment/config -H "Content-Type: application/json" -d '{"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", "connection.url": "http://elasticsearch:9200", "tasks.max": "1", "topics": "simulation_environment", "name": "elasticsearch-connector-environment", "type.name": "_doc", "value.converter": "org.apache.kafka.connect.json.JsonConverter", "value.converter.schemas.enable": "false", "schema.ignore": "true", "key.ignore": "true"}'

curl -X PUT localhost:8083/connectors/elasticsearch-connector-communication/config -H "Content-Type: application/json" -d '{"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", "connection.url": "http://elasticsearch:9200", "tasks.max": "1", "topics": "simulation_communication", "name": "elasticsearch-connector-communication", "type.name": "_doc", "value.converter": "org.apache.kafka.connect.json.JsonConverter", "value.converter.schemas.enable": "false", "schema.ignore": "true", "key.ignore": "true"}'

curl -X PUT localhost:8083/connectors/elasticsearch-connector-telemetria/config -H "Content-Type: application/json" -d '{"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", "connection.url": "http://elasticsearch:9200", "tasks.max": "1", "topics": "simulation_telemetria", "name": "elasticsearch-connector-telemetria", "type.name": "_doc", "value.converter": "org.apache.kafka.connect.json.JsonConverter", "value.converter.schemas.enable": "false", "schema.ignore": "true", "key.ignore": "true"}'

curl -X PUT localhost:8083/connectors/elasticsearch-connector-activity/config -H "Content-Type: application/json" -d '{"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", "connection.url": "http://elasticsearch:9200", "tasks.max": "1", "topics": "simulation_activity", "name": "elasticsearch-connector-activity", "type.name": "_doc", "value.converter": "org.apache.kafka.connect.json.JsonConverter", "value.converter.schemas.enable": "false", "schema.ignore": "true", "key.ignore": "true"}'
